[package]
name = "debot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
serde_json = "1.0"
num-rational = "0.3.2"
num = "0.2"
url = "2.2.2"
ethers = "2.0.3"
async-trait = "0.1.68"
ethers-middleware = "2.0.3"
actix-web = "4.3.1"
serde = { version = "1.0", features = ["derive"] }
actix-rt = "2.8.0"
chrono = "0.4.24"
futures = "0.3.28"
env_logger = "0.10.0"
log = "0.4.17"
anyhow = "1.0.71"
rand = "0.8.5"
lazy_static = "1.4.0"
